config/routes.rb
CarbantartoApp::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => 'home#index'

  
  devise_for :users
  resources :users
  resources :properties
  resources :vehicles do
    resources :users do
      
    end
  end

  resources :home


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  #root :to => 'main#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user

  attr_accessible :color, :manufacturer, :subtype, :user, :year
  
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  load_and_authorize_resource

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new
    Rails.logger.info("------------")
    Rails.logger.info(current_user)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = current_user.vehicles.build(params[:vehicle])
    
    #@vehicle = Vehicle.new(params[:vehicle])
    
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @vehicle.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h4>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :manufacturer, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :manufacturer, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :modell, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :subtype, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :year, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :color, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :color, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
   
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="page-header">
  <%= link_to vehicles_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @vehicle, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing vehicle</h1>
</div>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<div class="page-header">
  <%= link_to new_vehicle_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Vehicle
  <% end %>
  <h1>Vehicle list</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Manufacturer</th>
            <th>Modell</th>
            <th>Year</th>
            <th>Color</th>
            <th>Owner</th>
            <th></th>
            <% if can? :update, Vehicle %>
            <th></th>
            <% end %>
            <% if can? :destroy, Vehicle %>
            <th></th>
            <% end %>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @vehicles) do |vehicle| %>
            <td><%= vehicle.manufacturer %></td>
            <td><%= vehicle.subtype %></td>
            <td><%= vehicle.year %></td>
            <td><%= vehicle.color %></td>
            <td><%= vehicle.user.email %></td>
         
        <% if can? :read, Vehicle %>
        <td> 
          <%= link_to 'Show', vehicle %>
        </td>
        <% end %>
      
        <% if can? :update, Vehicle %>
        <td>
          <%= link_to 'Edit', edit_vehicle_path(vehicle) %>
        </td>
        <% end %>
        
        <% if can? :destroy, Vehicle %>
        <td>
          <%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <% end %>
        
      <% end %>
    </tbody>
  </table>
</div>

app/views/vehicles/new.html.erb
<div class="page-header">
  <%= link_to vehicles_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New vehicle</h1>
</div>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<div class="page-header">
  <%= link_to vehicles_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_vehicle_path(@vehicle), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show vehicle</h1>
</div>

<dl class="dl-horizontal">
  <dt>Manufacturer:</dt>
  <dd><%= @vehicle.manufacturer %></dd>

  <dt>Modell:</dt>
  <dd><%= @vehicle.subtype %></dd>

  <dt>Year:</dt>
  <dd><%= @vehicle.year %></dd>

  <dt>Color:</dt>
  <dd><%= @vehicle.color %></dd>

  <dt>Owner:</dt>
  <dd><%= @vehicle.user %></dd>

</dl>